zookeeper:
  image: netflixoss/exhibitor:1.5.2
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
linkerd:
  image: buoyantio/linkerd:0.9.0
  command: "/config.yaml"
  volumes:
   - ./linkerd/config.yaml:/config.yaml
  ports:
   - 9999:9999
   - 4140:4140
  links:
   - zookeeper