version: '2'

services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
  linkerd:
    image: buoyantio/linkerd:0.9.0
    command: "/config.yaml"
    volumes:
     - ./linkerd/config.yaml:/config.yaml
    ports:
     - 9999:9999
     - 4140:4140
    links:
     - zookeeper

  # Zipkin
  zipkin-mysql:
   image: openzipkin/zipkin-mysql
  zipkin:
   image: openzipkin/zipkin
   environment:
     - STORAGE_TYPE=mysql
     - MYSQL_HOST=zipkin-mysql
   ports:
     - 9410:9410
     - 9411:9411
   depends_on:
     - zipkin-mysql
  zipkin-dependencies:
   image: openzipkin/zipkin-dependencies
   entrypoint: crond -f
   environment:
     - STORAGE_TYPE=mysql
     - MYSQL_HOST=zipkin-mysql
     - MYSQL_USER=zipkin
     - MYSQL_PASS=zipkin
   depends_on:
     - zipkin-mysql