version: '2'

services:
  talk-service:
    image: scalatalk/talk-service
    command: -http.announce=zk!zookeeper:2181!/service/talk!0 -com.twitter.finagle.tracing.debugTrace=true -http.name=talk-service
    ports:
     - 8888:8888
     - 9990:9990
  speaker-service:
    image: scalatalk/speaker-service
    command: -talk.service.location=linkerd:4140 -http.announce=zk!zookeeper:2181!/service/speaker!0 -com.twitter.finagle.tracing.debugTrace=true -http.name=speaker-service
    ports:
     - 8889:8888
     - 9991:9990
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
     - 8080:8080
  linkerd:
    image: buoyantio/linkerd:0.9.0
    command: "/config.yaml"
    volumes:
     - ./linkerd/config.yaml:/config.yaml
    ports:
     - 9999:9999
     - 4140:4140
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9410:9410
      - 9411:9411
  zipkin-ui:
    image: openzipkin/zipkin-ui
    ports:
      - 8081:80