version: '2'

services:
  talk-service:
    image: scalatalk/talk-service
    command: -http.announce=zk!zookeeper:2181!/service/talk!0 -com.twitter.finagle.tracing.debugTrace=true -http.name=talk-service
    ports:
     - 8891:8888
     - 9991:9990
  speaker-service:
    image: scalatalk/speaker-service
    command: -talk.service.location=linkerd:4140 -http.announce=zk!zookeeper:2181!/service/speaker!0 -com.twitter.finagle.tracing.debugTrace=true -http.name=speaker-service
    ports:
     - 8892:8888
     - 9992:9990
  event-service:
   image: scalatalk/event-service
   command: -talk.service.location=linkerd:4140 -speaker.service.location=linkerd:4140 -http.announce=zk!zookeeper:2181!/service/event!0 -com.twitter.finagle.tracing.debugTrace=true -http.name=event-service
   ports:
    - 8893:8888
    - 9993:9990
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
     - 8080:8080
  linkerd:
    image: buoyantio/linkerd:0.9.0
    command: "/config.yaml"
    volumes:
     - ./linkerd/config/config.yaml:/config.yaml
    ports:
     - 9999:9999
     - 4140:4140
  zipkin:
    image: openzipkin/zipkin
    ports:
     - 9410:9410
     - 9411:9411
  zipkin-ui:
    image: openzipkin/zipkin-ui
    ports:
      - 8081:80
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:5.2.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
